version: "3.1"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8000:80
      - 443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
      - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
    links:
      - app

  app:
    restart: always
    build: ./
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - db
    env_file:
      - .env

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
      - ./docker/dump.sql:/tmp/dump.sql
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    volumes:
      - ./docker/adminer/hydra/adminer.css:/var/www/html/adminer.css
    ports:
      - 8080:8080
